// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectT1.Datos;

#nullable disable

namespace ProjectT1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240607043554_Migracion")]
    partial class Migracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectT1.Models.Marca", b =>
                {
                    b.Property<int?>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdMarca"));

                    b.Property<string>("NomMarca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMarca");

                    b.ToTable("Marca");

                    b.HasData(
                        new
                        {
                            IdMarca = 1,
                            NomMarca = "Toyota"
                        },
                        new
                        {
                            IdMarca = 2,
                            NomMarca = "Ford"
                        },
                        new
                        {
                            IdMarca = 3,
                            NomMarca = "Honda"
                        });
                });

            modelBuilder.Entity("ProjectT1.Models.Modelo", b =>
                {
                    b.Property<int?>("IdModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdModelo"));

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("NomModelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdModelo");

                    b.HasIndex("MarcaId");

                    b.ToTable("Modelo");

                    b.HasData(
                        new
                        {
                            IdModelo = 1,
                            MarcaId = 1,
                            NomModelo = "Camry"
                        },
                        new
                        {
                            IdModelo = 2,
                            MarcaId = 1,
                            NomModelo = "Corolla"
                        },
                        new
                        {
                            IdModelo = 3,
                            MarcaId = 1,
                            NomModelo = "RAV4"
                        },
                        new
                        {
                            IdModelo = 4,
                            MarcaId = 2,
                            NomModelo = "Focus"
                        },
                        new
                        {
                            IdModelo = 5,
                            MarcaId = 2,
                            NomModelo = "Mustang"
                        },
                        new
                        {
                            IdModelo = 6,
                            MarcaId = 2,
                            NomModelo = "Explorer"
                        },
                        new
                        {
                            IdModelo = 7,
                            MarcaId = 3,
                            NomModelo = "Civic"
                        },
                        new
                        {
                            IdModelo = 8,
                            MarcaId = 3,
                            NomModelo = "Accord"
                        },
                        new
                        {
                            IdModelo = 9,
                            MarcaId = 3,
                            NomModelo = "CR-V"
                        });
                });

            modelBuilder.Entity("ProjectT1.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstPer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModeloId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("NroPlaca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("ModeloId");

                    b.ToTable("Vehiculo");

                    b.HasData(
                        new
                        {
                            IdVehiculo = 1,
                            Anio = 2021,
                            Color = "Rojo",
                            EstPer = "Optimo",
                            ModeloId = 1,
                            NroPlaca = "ABC-1234"
                        },
                        new
                        {
                            IdVehiculo = 2,
                            Anio = 2022,
                            Color = "Azul",
                            EstPer = "Bueno",
                            ModeloId = 2,
                            NroPlaca = "MNO-3141"
                        },
                        new
                        {
                            IdVehiculo = 3,
                            Anio = 2023,
                            Color = "Amarillo",
                            EstPer = "Caducado",
                            ModeloId = 3,
                            NroPlaca = "JKL-1121"
                        },
                        new
                        {
                            IdVehiculo = 4,
                            Anio = 2024,
                            Color = "Rosado",
                            EstPer = "Buenas Condiciones ",
                            ModeloId = 4,
                            NroPlaca = "GHI-9101"
                        },
                        new
                        {
                            IdVehiculo = 5,
                            Anio = 2025,
                            Color = "Verde",
                            EstPer = "Malo",
                            ModeloId = 5,
                            NroPlaca = "XYZ-5678"
                        });
                });

            modelBuilder.Entity("ProjectT1.Models.Modelo", b =>
                {
                    b.HasOne("ProjectT1.Models.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("ProjectT1.Models.Vehiculo", b =>
                {
                    b.HasOne("ProjectT1.Models.Modelo", "Modelo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("ProjectT1.Models.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("ProjectT1.Models.Modelo", b =>
                {
                    b.Navigation("Vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
