// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectT1.Datos;

#nullable disable

namespace ProjectT1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240604030241_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectT1.Models.Marca", b =>
                {
                    b.Property<int?>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdMarca"));

                    b.Property<string>("NomMarca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMarca");

                    b.ToTable("Marca");

                    b.HasData(
                        new
                        {
                            IdMarca = 1,
                            NomMarca = "Marca1"
                        },
                        new
                        {
                            IdMarca = 2,
                            NomMarca = "Marca2"
                        },
                        new
                        {
                            IdMarca = 3,
                            NomMarca = "Marca3"
                        },
                        new
                        {
                            IdMarca = 4,
                            NomMarca = "Marca4"
                        },
                        new
                        {
                            IdMarca = 5,
                            NomMarca = "Marca5"
                        });
                });

            modelBuilder.Entity("ProjectT1.Models.Modelo", b =>
                {
                    b.Property<int?>("IdModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdModelo"));

                    b.Property<int?>("IdMarca")
                        .HasColumnType("int");

                    b.Property<int?>("MarcaIdMarca")
                        .HasColumnType("int");

                    b.Property<string>("NomModelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdModelo");

                    b.HasIndex("MarcaIdMarca");

                    b.ToTable("Modelo");

                    b.HasData(
                        new
                        {
                            IdModelo = 1,
                            IdMarca = 1,
                            NomModelo = "Modelo1"
                        },
                        new
                        {
                            IdModelo = 2,
                            IdMarca = 2,
                            NomModelo = "Modelo2"
                        },
                        new
                        {
                            IdModelo = 3,
                            IdMarca = 3,
                            NomModelo = "Modelo3"
                        },
                        new
                        {
                            IdModelo = 4,
                            IdMarca = 4,
                            NomModelo = "Modelo4"
                        },
                        new
                        {
                            IdModelo = 5,
                            IdMarca = 5,
                            NomModelo = "Modelo5"
                        });
                });

            modelBuilder.Entity("ProjectT1.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstPer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdModelo")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("ModeloIdModelo")
                        .HasColumnType("int");

                    b.Property<string>("NroPlaca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("ModeloIdModelo");

                    b.ToTable("Vehiculo");

                    b.HasData(
                        new
                        {
                            IdVehiculo = 1,
                            Anio = 2021,
                            Color = "Rojo",
                            EstPer = "Bueno",
                            IdModelo = 1,
                            NroPlaca = "Placa1"
                        },
                        new
                        {
                            IdVehiculo = 2,
                            Anio = 2022,
                            Color = "Azul",
                            EstPer = "Excelente",
                            IdModelo = 2,
                            NroPlaca = "Placa2"
                        },
                        new
                        {
                            IdVehiculo = 3,
                            Anio = 2023,
                            Color = "Amarillo",
                            EstPer = "Regular",
                            IdModelo = 3,
                            NroPlaca = "Placa3"
                        },
                        new
                        {
                            IdVehiculo = 4,
                            Anio = 2024,
                            Color = "Rosado",
                            EstPer = "Optimo",
                            IdModelo = 4,
                            NroPlaca = "Placa4"
                        },
                        new
                        {
                            IdVehiculo = 5,
                            Anio = 2025,
                            Color = "Verde",
                            EstPer = "Pesimo",
                            IdModelo = 5,
                            NroPlaca = "Placa5"
                        });
                });

            modelBuilder.Entity("ProjectT1.Models.Modelo", b =>
                {
                    b.HasOne("ProjectT1.Models.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaIdMarca");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("ProjectT1.Models.Vehiculo", b =>
                {
                    b.HasOne("ProjectT1.Models.Modelo", "Modelo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ModeloIdModelo");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("ProjectT1.Models.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("ProjectT1.Models.Modelo", b =>
                {
                    b.Navigation("Vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
